//
//  Types.swift
//  SQLiteKit
//
//  Created by Dot iTeam on 2026-06-04.
//

import Foundation
/// A SQLite value that can be bound to a prepared statement parameter.
public enum SQLParameter: Sendable {
    /// A UTF-8 text value.
    case text(String)
    /// A 32-bit integer value.
    case int(Int32)
    /// A 64-bit integer value.
    case integer(Int64)
    /// A binary large object value.
    case blob(Data)
    /// A floating-point value.
    case real(Double)
}
/// SQLite synchronous write mode used during database initialization.
public enum SQLiteSynchronous: String, Sendable {
    /// Disable synchronous writes.
    case off = "OFF"
    /// Use SQLite's normal synchronous mode.
    case normal = "NORMAL"
    /// Use SQLite's full synchronous mode.
    case full = "FULL"
}
/// SQLite temporary storage preference used during database initialization.
public enum SQLiteTempStore : String, Sendable {
    /// Store temporary tables and indices in memory.
    case memory = "MEMORY"
    /// Leave SQLite's default temporary storage behavior unchanged.
    case none
}
/// A schema entity category reported by SQLite.
public enum EntityType: String, Sendable {
    /// A table entry.
    case table
    /// A view entry.
    case view
    /// A trigger entry.
    case trigger
    /// An index entry.
    case index
    /// An unknown or unsupported entry type.
    case other = ""
}
/// Controls how strictly a declared schema is compared with the existing database schema.
public enum SchemaMatchMode: Sendable {
    /// Require constraints and relationships to match exactly where SQLiteKit can inspect them.
    case strict
    /// Accept existing compatible schema objects when the requested constraint is present.
    case flexible
}
/// A row that can be accessed by column name or by positional index.
public struct Row: Sendable, CustomStringConvertible {
    var dictionary: [String: Sendable?]
    var values: [Sendable?]
    /// Creates a row from an ordered list of optional column names and values.
    public init(entries: [(String?, Sendable?)]) {
        values = entries.map(\.1)
        let keyedEntries = entries.filter { $0.0 != nil }.map { ($0.0!, $0.1) }
        dictionary = Dictionary(uniqueKeysWithValues: keyedEntries)
    }
    /// Returns the value for a named column.
    public subscript(key: String) -> Sendable? {
        dictionary[key]
    }
    /// Returns the value at a positional column index.
    public subscript (index: Int) -> Sendable? {
        values[index]
    }
    /// A textual representation of the row's keyed values.
    public var description: String {
        dictionary.description
    }
}
/// The result of executing a statement that may return tabular rows.
public struct SQLResult: Sendable {
    /// Column names for the result when requested.
    public let header: [String]?
    /// Row values returned by the statement.
    public let records: [[Sendable]]
    /// Number of rows changed by the last statement on the database connection.
    public let affected: Int64
    /// Row identifier generated by the last successful insert.
    public let lastInsertRowId: Int64
}
/// The result of executing a mapper-backed query.
public struct SQLResultSet<T: Sendable>: Sendable {
    /// Values produced by the mapper.
    public let values: [T]
    /// Number of rows changed by the last statement on the database connection.
    public let affected: Int64
    /// Row identifier generated by the last successful insert.
    public let lastInsertRowId: Int64
}
/// The effect of executing a non-row-producing statement.
public struct SQLEffect: Sendable {
    /// Number of rows changed by the last statement on the database connection.
    public let affected: Int64
    /// Row identifier generated by the last successful insert.
    public let lastInsertRowId: Int64
}
